version: '3.9'
services:
  proxy:
    image: proxy
    container_name: proxy
    build: ./proxy
    ports:
      - 80:80
    restart: always
  next:
    image: next
    container_name: next
    build: ./next
    ports:
      - 3000
    restart: always
    depends_on:
      - proxy
  keystone:
    image: keystone
    container_name: keystone
    build: ./keystone
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - 3000
    restart: always
    depends_on:
      - proxy
