version: '3.9'
services:
  reverseproxy_service:
    image: reverseproxy_image
    container_name: reverseproxy_container
    build: .
    ports:
      - 80:80
      - 8080:8080
      - 8081:8081
    restart: always
  nginx_service:
    depends_on:
      - reverseproxy_service
    image: nginx_image
    container_name: nginx_container
    build: ./nginx
    ports:
      - 80
    restart: always
  apache_service:
    depends_on:
      - reverseproxy_service
    image: apache_image
    container_name: apache_container
    build: ./apache
    ports:
      - 80
    restart: always
