version: '3.9'
services:
  proxy:
    image: proxy
    container_name: proxy
    build: ./proxy
    restart: always
    ports:
      - 80:80
  next:
    image: next
    container_name: next
    build: ./next
    restart: always
    ports:
      - 3000
    depends_on:
      - proxy
  keystone:
    image: keystone
    container_name: keystone
    build: ./keystone
    restart: always
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}
    #   SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - 3000
    depends_on:
      - proxy
