version: '3.9'
services:
  reverseproxy_service:
    image: reverseproxy_image
    container_name: reverseproxy_container
    build: .
    ports:
      - 80:80
    restart: always
  nginx_service:
    image: nginx_image
    container_name: nginx_container
    build: ./nginx
    ports:
      - 80
    restart: always
  apache_service:
    image: apache_image
    container_name: apache_container
    build: ./apache
    ports:
      - 80
    restart: always
  node_service:
    image: node_image
    container_name: node_container
    build: ./node
    ports:
      - 3000
    restart: always
